name: "regenerate all maps and upload"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: "Install python requirements"
        run: |
           python3 -m venv venv              # Create virtual environment
           source venv/bin/activate          # Activate virtual environment
           pip install -r requirements.txt   # Install requirements

      - name: "Build PR"
        run: |
          source venv/bin/activate
          bash -x ./build.sh myoutdir
        env:
          PREVIOUS_COMMIT_PR: ${{ github.event.pull_request.base.sha }}
          PREVIOUS_COMMIT: ${{ github.event.before }}
          BUILD_MAPS: true

      - name: "Deploy Push"
        run: |
          ./deploy.sh myoutdir
        env:
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_KEY:  ${{ secrets.DEPLOY_KEY  }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
