name: "Generate, check, & deploy xcsoar-data-content"

on: 
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: "Install dependencies"
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            aerofiles
            iso3166
            pytz

      - name: "Set variables"
        run: |
          # Waypoint-by-country:
          echo "WPBC_SRC=waypoints" >> $GITHUB_ENV
          echo "WPBC_DST=waypoints" >> $GITHUB_ENV
          # Waypoints-special source:
          echo "WPS_SRC=waypoints-special" >> $GITHUB_ENV
      - name: "Create the release artefacts"
        run: |
          ./scripts/generate-web-waypoints-index.py  ${{ env.WPBC_SRC }}  ${{ env.WPBC_DST }}

      - name: "Concatenate all waypoints to xcsoar-waypoints.cup"
        run: |
          cat ${{ env.WPBC_SRC }}/*.cup | sort -b > ${{ env.WPBC_DST }}/xcsoar_waypoints.cup
          
      - name: "Check Waypoints"
        run: |
          set -e
          for each in ${{ env.WPBC_SRC }}/*.cup ; do python ./scripts/check-waypoints "${each}" ; done
          for each in  ${{ env.WPS_SRC }}/*.cup ; do python ./scripts/check-waypoints "${each}" ; done

      - name: "Install SSH key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: 'ffoooooooobar'
        if: ${{ github.event_name == 'push' }}

      - run: ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_HOST}} > ~/.ssh/known_hosts 
        if: ${{ github.event_name == 'push' }}

      - name: "Deploy to repository"
        run: |
          umask 077
          echo "${DEPLOY_KEY}" > ~/id_rsa
          # Waypoints-by-country: originals:
          rsync -av -e "ssh -p ${DEPLOY_PORT} -i ~/id_rsa" .${{ env.WPBC_SRC }}/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/waypoints/ --delete

          # TODO: Waypoints-by-country: generated artefacts:
          #rsync -av -e "ssh -p ${DEPLOY_PORT} -i ~/id_rsa" ${{ env.WPBC_DST }}/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/waypoints/generated/ --delete

          rsync -av -e "ssh -p ${DEPLOY_PORT} -i ~/id_rsa" {{ env.WPS_SRC }}/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/waypoints-special/ --delete
          rsync -av -e "ssh -p ${DEPLOY_PORT} -i ~/id_rsa" ./airspaces/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/airspaces/ --delete
        shell: bash
        if: ${{ github.event_name == 'push' }}
        env:
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
