name: "Check, generate, and deploy (if push to master) xcsoar-data-content"

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
  schedule:
    # 01h42Z everyday
    - cron: '42 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 0

      - name: "Install python requirements"
        run: |
          pip3 install -r requirements.txt

      - name: "Install shell requirements"
        run: |
          sudo apt -y install dos2unix

      - name: "Build PR"
        run: |
          bash -x ./build.sh
        env:
          PREVIOUS_COMMIT_PR: ${{ github.event.pull_request.base.sha }}
          PREVIOUS_COMMIT: ${{ github.event.before }}

      - name: "output repofile"
        run: |
          ls -R ./output/
          cat ./output/repository

      - name: "Deploy Push"
        run: |
          ./deploy.sh
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_KEY:  ${{ secrets.DEPLOY_KEY  }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
